// Package retro assembles the "process manual" — every always-on injection
// source unrolled into one linked markdown document (issue #153). The core is
// pure (InjectionSource + renderManual); the IO shell of collectors lives in
// collect.go / memory.go.
package retro

import (
	"fmt"
	"sort"
	"strings"
)

// Kind groups injection sources into manual sections.
type Kind string

const (
	KindSDLCPrompt  Kind = "sdlc-prompt"
	KindHelpText    Kind = "help-text"
	KindSkill       Kind = "skill"
	KindLessons     Kind = "lessons"
	KindAgentsChain Kind = "agents-chain"
	KindMemory      Kind = "memory"
)

// InjectionSource is one catalogued point where content enters an agent's context.
type InjectionSource struct {
	Kind  Kind
	Title string
	When  string // prose trigger: what injects this content
	Link  string // repo-root-relative path (+ optional #anchor)
	Body  string // full text for code-generated prompts; excerpt for file-backed sources
}

// sections fixes the display order and headings for each Kind.
var sections = []struct {
	kind    Kind
	heading string
}{
	{KindSDLCPrompt, "## sdlc-injected prompts"},
	{KindHelpText, "## Help text"},
	{KindSkill, "## Skills"},
	{KindLessons, "## Lessons"},
	{KindAgentsChain, "## AGENTS chain"},
	{KindMemory, "## Persisted memories"},
}

// renderManual is pure: sources → linked markdown, grouped by Kind in `sections`
// order. linkPrefix is prepended to every Link so the doc resolves from wherever
// it is written ("" = paths from repo root).
func renderManual(sources []InjectionSource, linkPrefix string) string {
	byKind := map[Kind][]InjectionSource{}
	for _, s := range sources {
		byKind[s.Kind] = append(byKind[s.Kind], s)
	}
	var b strings.Builder
	b.WriteString("# Process manual\n\n")
	b.WriteString("_Generated by `sdlc retro`. Every always-on injection source, linked to its origin. Do not hand-edit — regenerate._\n\n")
	for _, sec := range sections {
		items := byKind[sec.kind]
		if len(items) == 0 {
			continue
		}
		sort.SliceStable(items, func(i, j int) bool { return items[i].Title < items[j].Title })
		b.WriteString(sec.heading + "\n\n")
		for _, s := range items {
			fmt.Fprintf(&b, "### [%s](%s%s)\n\n", s.Title, linkPrefix, s.Link)
			if s.When != "" {
				fmt.Fprintf(&b, "**When:** %s\n\n", s.When)
			}
			if s.Body != "" {
				b.WriteString(s.Body)
				if !strings.HasSuffix(s.Body, "\n") {
					b.WriteString("\n")
				}
				b.WriteString("\n")
			}
		}
	}
	return b.String()
}
