package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/xianxu/ariadne/cmd/weave/internal/plan"
	"github.com/xianxu/ariadne/cmd/weave/internal/weavefs"
)

func TestCompileBuildsOwnerToolBeforeLeafGenerator(t *testing.T) {
	root := t.TempDir()
	base, leaf := filepath.Join(root, "base"), filepath.Join(root, "leaf")
	write := func(path, body string) {
		t.Helper()
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0755); err != nil {
			t.Fatal(err)
		}
	}
	write(filepath.Join(base, "construct/base.manifest"), "skill construct/local\n")
	write(filepath.Join(leaf, "construct/deps"), "substrate ../base\n")
	write(filepath.Join(base, "generator"), "#!/bin/sh\nmkdir -p \"$1\"\nprintf '%s\\n' '---' 'name: example' 'description: built generator' '---' 'GENERATED BY OWNER TOOL' > \"$1/SKILL.md\"\n")
	write(filepath.Join(base, "Makefile"), "tools:\n\tmkdir -p bin\n\tcp generator bin/fixture-generator\n")
	write(filepath.Join(base, "construct/local/example/.dynamic-skill"), "#!/bin/sh\n# weave-output: argv1\nfixture-generator \"$1\"\n")
	var out bytes.Buffer
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err != nil {
		t.Fatal(err, out.String())
	}
	got, err := os.ReadFile(filepath.Join(leaf, ".agents/skills/base-example/SKILL.md"))
	if err != nil || !strings.Contains(string(got), "GENERATED BY OWNER TOOL") {
		t.Fatalf("generated skill = %q, %v", got, err)
	}
	if _, err := os.Stat(filepath.Join(base, "construct/generated/example")); !os.IsNotExist(err) {
		t.Fatalf("generator wrote to base: %v", err)
	}
	if !strings.Contains(out.String(), filepath.Join(base, "bin")) {
		t.Fatalf("missing shell PATH guidance: %s", out.String())
	}
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err != nil {
		t.Fatal("repeat:", err)
	}
}

func TestCompileBuildFailurePreventsComposition(t *testing.T) {
	_, _, leaf := buildFixture(t)
	if err := os.WriteFile(filepath.Join(leaf, "Makefile"), []byte("tools:\n\tfalse\n"), 0644); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err == nil {
		t.Fatal("failed build accepted")
	}
	if _, err := os.Stat(filepath.Join(leaf, "AGENTS.md")); !os.IsNotExist(err) {
		t.Fatalf("composition ran after failed build: %v", err)
	}
}

func TestCompileRetiresDisconnectedOutputsPreservesAuthoredFiles(t *testing.T) {
	_, _, leaf := buildFixture(t)
	var out bytes.Buffer
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err != nil {
		t.Fatal(err)
	}
	// Edit one formerly generated face and remove the final base. Exact identity
	// evidence permits retiring the unchanged link, even with no base left in graph.
	authored := filepath.Join(leaf, "CLAUDE.md")
	if err := os.WriteFile(authored, []byte("authored replacement\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(leaf, "construct/deps"), nil, 0644); err != nil {
		t.Fatal(err)
	}
	// No prose production means the edited face is a retired replacement.
	if err := os.WriteFile(filepath.Join(leaf, "construct/base.manifest"), nil, 0644); err != nil {
		t.Fatal(err)
	}
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err != nil {
		t.Fatal(err)
	}
	if got, err := os.ReadFile(authored); err != nil || string(got) != "authored replacement\n" {
		t.Fatalf("authored face changed: %q %v", got, err)
	}
	if _, err := os.Lstat(filepath.Join(leaf, "shared.md")); !os.IsNotExist(err) {
		t.Fatalf("disconnected generated link survived: %v", err)
	}
}

func TestCompileMountsDataPerOwnerAndRetiresRemovedDeclarations(t *testing.T) {
	root := t.TempDir()
	base, leaf, data := filepath.Join(root, "base"), filepath.Join(root, "leaf"), filepath.Join(root, "data")
	for _, dir := range []string{base, leaf, data} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			t.Fatal(err)
		}
	}
	for _, args := range [][]string{{"init", "-q"}, {"remote", "add", "origin", "https://github.com/example/data.git"}} {
		cmd := exec.Command("git", args...)
		cmd.Dir = data
		if output, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git: %v %s", err, output)
		}
	}
	mkfile(t, filepath.Join(data, "payload"), "authored data\n")
	mkfile(t, filepath.Join(base, "construct/base.manifest"), "prose AGENTS.local.md\n")
	mkfile(t, filepath.Join(base, "AGENTS.local.md"), "base prose\n")
	row := "data https://github.com/example/data.git mounted\n"
	mkfile(t, filepath.Join(base, "construct/deps"), row)
	mkfile(t, filepath.Join(leaf, "construct/deps"), "substrate ../base\n"+row)
	var out bytes.Buffer
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err != nil {
		t.Fatal(err)
	}
	for _, owner := range []string{base, leaf} {
		got, err := os.ReadFile(filepath.Join(owner, "mounted/payload"))
		if err != nil || string(got) != "authored data\n" {
			t.Fatalf("owner %s data = %q %v", owner, got, err)
		}
	}
	mkfile(t, filepath.Join(base, "construct/deps"), "")
	mkfile(t, filepath.Join(leaf, "construct/deps"), "substrate ../base\n")
	if err := run(weavefs.OSFS{}, leaf, plan.TargetAll, false, &out); err != nil {
		t.Fatal(err)
	}
	for _, owner := range []string{base, leaf} {
		if _, err := os.Lstat(filepath.Join(owner, "mounted")); !os.IsNotExist(err) {
			t.Fatalf("stale mount %s: %v", owner, err)
		}
	}
	if _, err := os.Stat(filepath.Join(leaf, "AGENTS.md")); err != nil {
		t.Fatal("data reconciliation removed artifacts:", err)
	}
	if got, err := os.ReadFile(filepath.Join(data, "payload")); err != nil || string(got) != "authored data\n" {
		t.Fatal("data source changed")
	}
}
