package recovery

// observeEvidence is the common evidence query (#279).
const observeEvidence = "`sdlc issue show N --json`"

// Catalog is every workflow verb's contract. TestRecoveryContractsAreProven
// (cmd/sdlc) derives the required verb set from the command tree and fails on a
// verb with neither a contract nor an Exempt entry, and on any named test that
// does not exist.
var Catalog = []Contract{
	{
		Verbs:         []string{"claim"},
		Class:         ConvergentRetry,
		Effects:       "one compare-and-swap on the card: open → working, `started` and the claimant (#277); `--adopt` stamps an owner on unattributed working work; on the owner's own moved work it relocates the claimant. Then a local mirror refresh. Never pushes main.",
		Evidence:      observeEvidence + ": card.status, assignment.claimant, assignment.relation.",
		Preconditions: "the card exists and its details are on main (re-checked before the push); `--adopt` needs working/blocked with no owner; relocation needs `sdlc move`'s record.",
		Repeat:        "the owning workspace: \"already claimed by this workspace; nothing to do\" (no write). Another workspace's card: refused, naming the owner. A working card with no owner: refused toward `--adopt`.",
		LostResponse:  "rerun the same command — the card decides: if this workspace's claim landed, the rerun reports it; if not, it claims. A concurrent change refuses (\"changed while claiming\"); inspect before retrying.",
		Ends:          "the card leaves working (close, set-status) or is reclaimed (`sdlc reclaim`): the claim then names its new owner.",
		Proofs: []Proof{
			{"one winner among concurrent claims; the loser publishes no ownership", []string{"TestClaimRaceHasExactlyOneWinner"}},
			{"one winner among concurrent adopts", []string{"TestAdoptRaceHasExactlyOneWinner"}},
			{"an owner's repeat is a no-op; others are refused", []string{"TestClaimDecisionOwnership", "TestVerbContractTable", "TestClaimDryRunOwnerRepeatWritesNothing"}},
			{"a lost response is settled by rerunning", []string{"TestClaimRerunSettlesALostResponse"}},
			{"relocation needs move's record; a repeat is a no-op", []string{"TestRelocationAfterMoveAndRepair"}},
			{"an unreachable tracker refuses without local mutation", []string{"TestClaimOfflineRefusesWithoutLocalMutation"}},
		},
	},
	{
		Verbs:         []string{"reclaim"},
		Class:         ConvergentRetry,
		Effects:       "inspect (no --expect) writes nothing. Confirm: one compare-and-swap moving the claimant to this workspace, with Reclaim-From/To/Reason trailers on the tracker commit (#278). No worktree is touched.",
		Evidence:      observeEvidence + ": assignment; `sdlc reclaim --issue N` lists past reclaims with reasons.",
		Preconditions: "an owned working/blocked/codecomplete card; --expect equal to the revision inspected; a one-line --reason.",
		Repeat:        "after success: \"already this workspace's; nothing to reclaim\". With a stale --expect: refused (\"changed since you inspected it\").",
		LostResponse:  "rerun the same command — the card decides (already yours: done; still at REV: retried).",
		Ends:          "any later card change (another reclaim, a claim, a status change) invalidates the inspected revision.",
		Proofs: []Proof{
			{"transfers responsibility; the old owner's gates refuse; no worktree touched", []string{"TestReclaimTransfersResponsibility"}},
			{"stale --expect refused; a lost response is settled by rerunning", []string{"TestReclaimStaleAndLostResponse"}},
			{"one winner among concurrent reclaims", []string{"TestReclaimRaceHasExactlyOneWinner"}},
			{"only the operator's command reaches the transfer", []string{"TestReclaimIsOnlyOperatorInvoked"}},
		},
	},
	{
		Verbs:         []string{"start-plan"},
		Class:         ConvergentRetry,
		Effects:       "creates the issue branch at main (or switches to it) and refreshes the local mirror. Nothing is pushed.",
		Evidence:      observeEvidence + ": branch, workspaces.",
		Preconditions: "the card is working and owned by this workspace; on the resting branch or the issue branch; no tracked changes; the branch carries no other issue's unlanded commits (#272).",
		Repeat:        "on the branch: re-checks and does nothing; the branch exists elsewhere: switches to it.",
		LostResponse:  "no remote effect; rerun.",
		Ends:          "ownership moves (reclaim) — the old workspace is refused.",
		Proofs: []Proof{
			{"creates or reuses the branch", []string{"TestPreparePlanningBranchRefusesMissingDetailsAndReusesBranch", "TestStartPlanRequiresClaimAndPreparesBranch"}},
			{"refuses an unlanded base", []string{"TestPreparePlanningBranchRefusesAnUnlandedBase"}},
			{"refuses a non-owner", []string{"TestOwnershipGatesRefuseForeignAndUnknown"}},
		},
	},
	{
		Verbs:         []string{"change-code"},
		Class:         ConvergentRetry,
		Effects:       "runs the planning gates (plan-quality writes its ledger; estimate-quality dispatches a judge); records the flow and refreshes the mirror; one local commit of the design. Never pushes.",
		Evidence:      observeEvidence + ": checkpoints.flow, checkpoints.reviews[plan].",
		Preconditions: "on the issue branch (start-plan first); owned by this workspace; on the full flow, a plan that clears plan-quality and a reconciled estimate.",
		Repeat:        "an unchanged plan passes plan-quality without a new review; the branch and commit converge. estimate-quality re-dispatches each run, so its advisory text may differ.",
		LostResponse:  "local only; rerun.",
		Ends:          "ownership moves (reclaim).",
		Proofs: []Proof{
			{"plan-quality converges across rounds", []string{"TestPlanQualityConvergesAcrossRounds"}},
			{"the in-place branch is reused on a rerun", []string{"TestCreateInPlaceBranch_RealRepo_IdempotentRerun"}},
			{"refuses a non-owner", []string{"TestOwnershipGatesRefuseForeignAndUnknown"}},
		},
	},
	{
		Verbs:         []string{"milestone-close"},
		Class:         NonRepeatable,
		Effects:       "dispatches the boundary review (a new round in the issue's gate ledger and review sidecar); on a finalizing verdict ticks the milestone and logs it. No commit and no card write: the agent commits with the printed trailers.",
		Evidence:      observeEvidence + ": checkpoints.reviews[Mx] (verdict, open_blocking).",
		Preconditions: "owned by this workspace; measured actual; the milestone's window since the previous verdict.",
		Repeat:        "dispatches a new review round. A refused (REWORK/open blocking) close changes nothing durable but the ledger; fix and re-run.",
		LostResponse:  "read the ledger and sidecar (checkpoints) before re-running — a finished review must not be re-dispatched just to learn its verdict.",
		Ends:          "the milestone is ticked; later work belongs to the next boundary.",
		Proofs: []Proof{
			{"REWORK does not finalize; SHIP finalizes", []string{"TestRunMilestoneClose_REWORK_DoesNotFinalize", "TestRunMilestoneClose_SHIP_Finalizes"}},
			{"an issue changed during the review does not finalize", []string{"TestCloseCommands_IssueChangedDuringBoundaryReview_DoesNotFinalize"}},
			{"its verdict and scoped open findings are observable", []string{"TestObserveMilestonesThroughTheRealGates"}},
		},
	},
	{
		Verbs:         []string{"close"},
		Class:         NonRepeatable,
		Effects:       "dispatches the whole-issue review; on SHIP, behind a recovery receipt: an evidence commit on the branch, codecomplete on the card bound to it {token, reviewed head, evidence commit}, then a mirror commit. FIX-THEN-SHIP stores the receipt unstarted.",
		Evidence:      observeEvidence + ": completion (token, evidence_commit), checkpoints.reviews[close]; `sdlc issue recovery list`.",
		Preconditions: "on the issue branch; owned by this workspace; no unfinished close in progress (finish it with `sdlc issue recovery reconcile --issue N`).",
		Repeat:        "a new review and a new close generation that rebinds the card; the earlier evidence commit stays in history. Do not re-run to recover — reconcile.",
		LostResponse:  "`sdlc issue recovery reconcile --issue N` drives the receipt, probing before repeating any effect.",
		Ends:          "a landing completes the card (done); a reopen or a newer close supersedes this generation.",
		Proofs: []Proof{
			{"evidence before codecomplete, bound to the reviewed head", []string{"TestTrackerCloseCommitsEvidenceAndPublishesBoundCard", "TestCompletionCommitsEvidenceBeforeCodecomplete"}},
			{"FIX-THEN-SHIP lands evidence after the fixes", []string{"TestTrackerCloseFixThenShipLandsEvidenceAfterTheFixes", "TestTrackerCloseFixThenShipSurvivesASweepingFixCommit"}},
			{"a re-close supersedes an unstarted close; an older review cannot win", []string{"TestTrackerReCloseSupersedesAnUnstartedClose", "TestNewestCloseRefusesAnOlderReviewThanTheCardsClose"}},
			{"a re-run after SHIP is a new generation", []string{"TestCloseRerunAfterShipStartsANewGeneration"}},
			{"an interrupted mirror commit is finished by reconcile", []string{"TestReconcileRetriesAnInterruptedCloseMirror"}},
			{"preconditions refuse before the review runs", []string{"TestTrackerCloseRefusesPreconditionsBeforeReview", "TestOwnershipGatesRefuseForeignAndUnknown"}},
		},
	},
	{
		Verbs:         []string{"issue recovery reconcile"},
		Class:         ConvergentRetry,
		Effects:       "drives each unfinished receipt (close, issue new, move-detail) to its end, probing an uncertain effect before repeating it; settles closes whose evidence already landed; finishes an interrupted close mirror.",
		Evidence:      "`sdlc issue recovery list`; " + observeEvidence + ".",
		Preconditions: "run from the checkout on the receipt's branch (another worktree is refused).",
		Repeat:        "nothing left to do: reports so and changes nothing.",
		LostResponse:  "rerun — it re-probes from the durable receipt.",
		Ends:          "a superseded close is released, never driven.",
		Proofs: []Proof{
			{"refuses another worktree", []string{"TestRecoveryReconcileRefusesAnotherWorktree"}},
			{"an interrupted handoff is finished", []string{"TestMoveDetailInterruptedRecordIsFinishedByReconcile"}},
			{"every declared effect survives interruption", []string{"TestReceiptGeneratedInterruptionsAtEveryDeclaredEffect"}},
			{"a rerun after the mirror commit is a no-op", []string{"TestReconcileRetriesAnInterruptedCloseMirror"}},
		},
	},
	{
		Verbs:         []string{"pr"},
		Class:         ConvergentRetry,
		Effects:       "pushes the issue branch and opens its pull request, or updates the open one.",
		Evidence:      "the printed PR URL; `gh pr view`.",
		Preconditions: "an issue branch (not a resting branch); handed-off details unchanged.",
		Repeat:        "in a numbered workspace: \"updated PR #N\" (converges). In an ordinary checkout `gh pr create` refuses an existing PR — check for it before re-running.",
		LostResponse:  "rerun in a numbered workspace; in an ordinary checkout check `gh pr view` first.",
		Ends:          "the PR merges or closes; a merged branch name is never reused (#148).",
		Proofs: []Proof{
			{"a repeat updates the open PR", []string{"TestLandingPRUpdatesOpenPR"}},
			{"a changed head is detected", []string{"TestLandingPRChangedHead"}},
			{"an ordinary checkout's repeat is refused by gh without change", nil},
		},
	},
	{
		Verbs:         []string{"merge"},
		Class:         ConvergentRetry,
		Effects:       "merges the PR, completes the issue's card (done, landed commit), archives the issue family on main and cleans up the branch.",
		Evidence:      observeEvidence + ": landing.outcome, landing.archived; the printed `Recovery: sdlc merge --branch B --yes`.",
		Preconditions: "a reviewed branch whose head is unchanged since close; a clean tree; confirmation (--yes without a TTY).",
		Repeat:        "an already-merged PR resumes post-merge cleanup; a reused branch name is refused (#148); after full success from rest, refused.",
		LostResponse:  "run the printed `sdlc merge --branch B --yes`: it observes merged / integrated / archived / at rest and continues from there.",
		Ends:          "the card was reopened or closed again (another generation): completion is refused.",
		Proofs: []Proof{
			{"resumes cleanup after a merge already happened", []string{"TestRunMerge_ResumeMergedPR_FinishesCleanup"}},
			{"refuses unmerged commits on a merged branch name", []string{"TestRunMerge_ResumeMergedPR_UnmergedCommits_Refuses"}},
			{"interrupted landings resume from observation", []string{"TestLandingInterruptedCleanup", "TestLandingInterruptedIntegration", "TestLandingRefusesUncertainty"}},
			{"a re-closed generation is left alone", []string{"TestPublishFlipLeavesAReclosedGenerationAlone"}},
			{"a reopened card is left alone", []string{"TestLandingLeavesAReopenedCardAlone"}},
			{"the archive retry proof is deterministic", []string{"TestLandingArchiveAtomicAndRetryProof", "TestDurableLandingProofSurvivesACardChangeAfterArchive"}},
		},
	},
	{
		Verbs:         []string{"push"},
		Class:         ConvergentRetry,
		Effects:       "from main: pushes, completes codecomplete cards whose evidence is now on main, archives done issues (commit + push).",
		Evidence:      observeEvidence + ": landing.",
		Preconditions: "on main, clean apart from a prepared archive move; the pre-merge gates.",
		Repeat:        "completed cards and archived issues are not touched again (inference from the convergent completion and archive steps).",
		LostResponse:  "rerun `sdlc push`: an interrupted archive (moved but uncommitted) is resumed first.",
		Ends:          "a reopened or re-closed card is not completed.",
		Proofs: []Proof{
			{"codecomplete flips then archives", []string{"TestPushPublishSequence_CodecompleteFlippedThenArchived"}},
			{"an interrupted archive is resumed", []string{"TestRecoverInterruptedArchiveCommitsAndPushes"}},
			{"a repeat after success changes nothing", nil},
		},
	},
	{
		Verbs:         []string{"move"},
		Class:         DuplicateSafeRefusal,
		Effects:       "records the relocation, switches the source slot to rest and the destination to the issue branch, verifies both, then moves the owner on the card (#277).",
		Evidence:      observeEvidence + ": assignment.claimant, workspaces.",
		Preconditions: "same repository; the source on an issue branch, the destination at rest; no git operation in progress; clean.",
		Repeat:        "the source is now at rest: refused, nothing changes.",
		LostResponse:  "a failed owner update warns and names `sdlc claim --issue N` at the destination, which finishes it; a failed first switch moved nothing and leaves no record.",
		Ends:          "another move or a reclaim overwrites the relocation.",
		Proofs: []Proof{
			{"moves the branch and its owner", []string{"TestMoveToPrimary", "TestMoveRelocatesItsOwner"}},
			{"refusals change nothing", []string{"TestMoveRefusals"}},
			{"a failed first switch leaves no record", []string{"TestMoveFirstSwitchFailureLeavesNoRecord"}},
			{"a failed owner update is repaired by claim", []string{"TestRelocationAfterMoveAndRepair"}},
		},
	},
	{
		Verbs:         []string{"issue set-status", "set-status", "issue set-title", "issue set-estimate", "issue set-github"},
		Class:         ConvergentRetry,
		Effects:       "one compare-and-swap on the card field (entering working also stamps the claimant, #277); a local mirror refresh.",
		Evidence:      observeEvidence + ": card.",
		Preconditions: "the lifecycle guards (--force waives them, never ownership); done and codecomplete belong to close and merge.",
		Repeat:        "\"already has that …\" — no write.",
		LostResponse:  "rerun the same command — the card decides. A concurrent change refuses (\"changed concurrently\").",
		Ends:          "another card change since you read it.",
		Proofs: []Proof{
			{"guards and claimant stamping", []string{"TestStatusDecisionRecordsOrRefusesTheClaimant", "TestCheckTransitionGuards_ReopenNeedsLogEntry"}},
			{"a lost response is settled by rerunning", []string{"TestSetStatusRerunSettlesALostResponse"}},
		},
	},
	{
		Verbs:         []string{"issue new"},
		Class:         NonRepeatable,
		Effects:       "behind a creation receipt: reserves the next ID on the tracker, then writes the details locally (committed narrowly on a feature branch).",
		Evidence:      "the printed path; `sdlc issue recovery list`.",
		Preconditions: "a branch (not detached).",
		Repeat:        "files another issue with a new ID.",
		LostResponse:  "`sdlc issue recovery reconcile` resumes the receipt (a reservation that published nothing is released).",
		Ends:          "the details land on main (`sdlc issue move-detail`).",
		Proofs: []Proof{
			{"concurrent filings get distinct IDs", []string{"TestIssueNewRaceAllocatesDistinctIDs", "TestCreationLostRaceReallocatesWithoutDuplicateID"}},
			{"an uncertain push resumes from the receipt", []string{"TestCreationUncertainPushResumesFromDurableReceipt"}},
		},
	},
	{
		Verbs:         []string{"issue move-detail"},
		Class:         DuplicateSafeRefusal,
		Effects:       "behind a transfer receipt: records the handoff on the card, publishes the initial details to main, removes the source copy.",
		Evidence:      "the details on main; " + observeEvidence + ".",
		Preconditions: "no unfinished receipt; a free destination; no hand-edited card field.",
		Repeat:        "refused once the handoff exists (inference: the destination is occupied).",
		LostResponse:  "`sdlc issue recovery reconcile` finishes an interrupted handoff.",
		Ends:          "the details are on main; later edits ride the issue branch.",
		Proofs: []Proof{
			{"an interrupted handoff is finished by reconcile", []string{"TestMoveDetailInterruptedRecordIsFinishedByReconcile"}},
			{"refuses an occupied destination", []string{"TestMoveDetailRefusesExistingDestinationAndUnreadableSource"}},
		},
	},
	{
		Verbs:         []string{"issue sync"},
		Class:         ConvergentRetry,
		Effects:       "commits the issue's details locally on the issue branch; pushes nothing.",
		Evidence:      "`git log -- <details>`.",
		Preconditions: "the issue branch in a tracker repository.",
		Repeat:        "nothing new to commit (inference).",
		LostResponse:  "local only; rerun.",
		Ends:          "not applicable: a local commit only.",
		Proofs: []Proof{
			{"commits locally and never pushes", []string{"TestIssueSync_DefaultDoesNotPush", "TestIssueSync_FromFeatureBranchCommitsOnThatBranch"}},
			{"a repeat with nothing new changes nothing", nil},
		},
	},
	{
		Verbs:         []string{"issue show"},
		Class:         ReadOnly,
		Effects:       "none besides the tracker fetch's remote-tracking ref update.",
		Evidence:      "its own output (`--json`, schema_version 1, #279).",
		Preconditions: "none; any checkout of the repository, or --repo.",
		Repeat:        "a fresh observation.",
		LostResponse:  "rerun.",
		Ends:          "each answer is as of its observed_at and tracker commit; stale/unknown sections are not negative evidence.",
		Proofs: []Proof{
			{"writes nothing local", []string{"TestObserveAParkedSlotFromAnotherCheckout"}},
			{"stale reads say so", []string{"TestObserveStaleTrackerSaysSo"}},
		},
	},
}

// Exempt are mutating commands outside the issue workflow's recovery
// contracts, each with the reason it needs none here.
var Exempt = map[string]string{
	"issue migrate":      "one-time tracker cutover with its own --apply/--reconcile procedure (atlas: issue-tracker-migration)",
	"issue publish":      "retired in tracker repositories (#252); kept only to refuse with directions",
	"project new":        "project artifacts, not the issue workflow",
	"project set-status": "project artifacts, not the issue workflow",
	"project retro":      "project artifacts, not the issue workflow",
	"project close":      "project artifacts, not the issue workflow",
	"migrate":            "cross-repository artifact move tool (#179), outside the issue workflow",
	"fetch":              "refreshes remote-tracking refs only; no workflow state",
}
