package recovery

// observeEvidence is the common evidence query (#279).
const observeEvidence = "`sdlc issue show N --json`"

// Catalog is every workflow verb's contract. TestRecoveryContractsAreProven
// (cmd/sdlc) derives the required verb set from the command tree and fails on a
// verb with neither a contract nor an Exempt entry, and on any named test that
// does not exist.
var Catalog = []Contract{
	{
		Verbs:         []string{"claim"},
		Class:         ConvergentRetry,
		Effects:       "one tracker commit recording this workspace as owner, the lock (#277, #283), on every named card (#284: a set is all or nothing, each card decided on the bytes each attempt reads): the claimant, `updated` and a first `started`, spending any release; the status is unchanged (an open card stays open until start-plan; unowned started work is taken over in its status). A handed-off card (its release names a branch) is one issue at a time: the branch is fetched and checked out at the recorded tip. Afterwards a resting branch fast-forwards to the fetched main, or claim warns why not; elsewhere, details differing from main's are named. On the owner's own moved work it relocates the claimant. Never pushes main. A legacy repository (no tracker) has no owner, and its claim performs open → working.",
		Evidence:      observeEvidence + ": card.status, assignment.claimant, assignment.relation.",
		Preconditions: "every card exists, holds the lock's status (open, working, blocked, codecomplete), is unowned (or already this workspace's), and its details are on main (re-checked before the push). A handoff takeover also needs the release to name the issue's own branch, a clean resting branch here, the fetched tip equal to the recorded head, and no diverged local copy — all checked before the card is written; relocation needs `sdlc move`'s record.",
		Repeat:        "the owning workspace, at any status that holds the lock: \"already claimed by this workspace; nothing to do\" (no write); a takeover whose response or switch was lost resumes on the issue's branch as the publication remote has it (its only writer is the owner), refusing a diverged local copy. Another workspace's card: refused, naming the owner.",
		LostResponse:  "rerun the same command — the cards decide: if this workspace's claim landed, the rerun reports it; if not, it claims. A member claimed by a peer meanwhile fails the set, naming it.",
		Ends:          "the card reaches a terminal status (the owner stays as attribution, no longer a lock) or is reclaimed (`sdlc reclaim`): the claim then names its new owner. start-plan and close move the status, not the claim.",
		Proofs: []Proof{
			{"one winner among concurrent claims; the loser publishes no ownership", []string{"TestClaimRaceHasExactlyOneWinner"}},
			{"a set is one tracker commit; a contested member fails it whole; a benign change is re-decided", []string{"TestClaimSetDecision", "TestClaimSetIsOneTrackerCommit", "TestClaimSetRace", "TestChangeCardsRedecidesAfterARace"}},
			{"the checkout is refreshed after claiming, never over a local change", []string{"TestClaimRefreshesTheCheckout"}},
			{"one winner among concurrent takeovers of an unowned started card", []string{"TestAdoptRaceHasExactlyOneWinner"}},
			{"a handoff is resumed at exactly its tip, after every check", []string{"TestHandoffAndTakeover", "TestTakeoverRefusals", "TestClaimSetRefusesAHandedOffMember"}},
			{"a lost takeover switch or response is finished by rerunning; a diverged local copy refuses, an ahead one is resumed on", []string{"TestTakeoverRerunFinishesTheSwitch", "TestTakeoverLostResponseRerunResumes", "TestTakeoverRerunWithALocalCopy"}},
			{"a re-release after the fetch refuses the takeover", []string{"TestTakeoverRefusesAReReleaseBeforeTheWrite"}},
			{"a card claimed before #277 is taken over in its status", []string{"TestPlainClaimTakesOverAPre277Codecomplete", "TestClaimSetLostResponseAndTakeover"}},
			{"an owner's repeat is a no-op; others are refused", []string{"TestClaimDecisionOwnership", "TestVerbContractTable", "TestClaimDryRunOwnerRepeatWritesNothing"}},
			{"claim never moves status, over the model's status × owner product", []string{"TestClaimNeverMovesStatus"}},
			{"a lost response is settled by rerunning", []string{"TestClaimRerunSettlesALostResponse"}},
			{"a lost push acknowledgement is reported uncertain, never replayed", []string{"TestUpdateMany_LostAcknowledgmentIsUncertainWithoutReplay"}},
			{"relocation needs move's record; a repeat is a no-op", []string{"TestRelocationAfterMoveAndRepair"}},
			{"an unreachable tracker refuses without local mutation", []string{"TestClaimOfflineRefusesWithoutLocalMutation"}},
		},
	},
	{
		Verbs:         []string{"reclaim"},
		Class:         ConvergentRetry,
		Effects:       "inspect (no --expect) writes nothing. Confirm: one compare-and-swap moving the claimant to this workspace, with Reclaim-From/To/Reason trailers on the tracker commit (#278). No worktree is touched.",
		Evidence:      observeEvidence + ": assignment; `sdlc reclaim --issue N` lists past reclaims with reasons.",
		Preconditions: "an owned card whose status holds the lock (open, working, blocked or codecomplete — an open shaping claim included, #283); --expect equal to the revision inspected; a one-line --reason.",
		Repeat:        "after success: \"already this workspace's; nothing to reclaim\". With a stale --expect: refused (\"changed since you inspected it\").",
		LostResponse:  "rerun the same command — the card decides (already yours: done; still at REV: retried).",
		Ends:          "any later card change (another reclaim, a claim, a status change) invalidates the inspected revision.",
		Proofs: []Proof{
			{"transfers responsibility; the old owner's gates refuse; no worktree touched", []string{"TestReclaimTransfersResponsibility"}},
			{"the reclaimable statuses come from the model, an owned open card included", []string{"TestReclaimDecision"}},
			{"stale --expect refused; a lost response is settled by rerunning", []string{"TestReclaimStaleAndLostResponse"}},
			{"one winner among concurrent reclaims", []string{"TestReclaimRaceHasExactlyOneWinner"}},
			{"only the operator's command reaches the transfer", []string{"TestReclaimIsOnlyOperatorInvoked"}},
		},
	},
	{
		Verbs:         []string{"start-plan"},
		Class:         ConvergentRetry,
		Effects:       "creates the issue branch at main (or switches to it), carrying uncommitted edits to this issue's own details; then, on an open card, one compare-and-swap starting it (open → working, `started` if absent, #283); then refreshes the local mirror, then pushes the issue branch with a lease on the last-fetched copy (#286; a failed push warns and the next boundary pushes again). The card write publishes to the tracker; main is never pushed.",
		Evidence:      observeEvidence + ": card.status, branch, workspaces.",
		Preconditions: "the card is open or working and owned by this workspace (claim first); on the resting branch or the issue branch; no tracked changes other than this issue's own details; the branch carries no other issue's unlanded commits (#272).",
		Repeat:        "on the branch with the card working: re-checks and does nothing; the branch exists elsewhere: switches to it; the card still open (a lost start write): starts it.",
		LostResponse:  "rerun the same command — branch first, then card: the branch converges, and the card is started only if it is still open. A concurrent card change (a reclaim) refuses, naming the branch left in this checkout.",
		Ends:          "ownership moves (reclaim) — the old workspace is refused.",
		Proofs: []Proof{
			{"origin's issue branch equals HEAD after the verb, a rerun included; a rebase is force-pushed with the lease (#286)", []string{"TestBoundaryVerbsPushTheIssueBranch", "TestBoundaryPushLeases", "TestStartPlanRerunPushes"}},
			{"creates or reuses the branch", []string{"TestPreparePlanningBranchRefusesMissingDetailsAndReusesBranch", "TestStartPlanRequiresClaimAndPreparesBranch"}},
			{"refuses an unlanded base", []string{"TestPreparePlanningBranchRefusesAnUnlandedBase"}},
			{"refuses a non-owner", []string{"TestOwnershipGatesRefuseForeignAndUnknown"}},
			{"starts the owner's open card along the model's start edge, keeping the claim's stamp; a rerun is a no-op", []string{"TestStartDecision", "TestShapeUnderClaimThenStart"}},
			{"carries only this issue's own details edits", []string{"TestPlanningDirtyBlocking", "TestShapeUnderClaimThenStart"}},
		},
	},
	{
		Verbs:    []string{"change-code"},
		Class:    ConvergentRetry,
		Effects:  "runs the planning gates (plan-quality writes its ledger; estimate-quality dispatches a judge); records the flow and refreshes the mirror; one local commit of the design. Never pushes.",
		Evidence: observeEvidence + ": checkpoints.flow, checkpoints.reviews[plan].",
		Preconditions: "on the issue branch (start-plan first); owned by this workspace and started — a claimed but still open card refuses toward start-plan (#283); " +
			"on the full flow, a plan that clears plan-quality and a reconciled estimate.",
		Repeat:       "an unchanged plan passes plan-quality without a new review; the branch and commit converge. estimate-quality re-dispatches each run, so its advisory text may differ.",
		LostResponse: "local only; rerun.",
		Ends:         "ownership moves (reclaim).",
		Proofs: []Proof{
			{"plan-quality converges across rounds", []string{"TestPlanQualityConvergesAcrossRounds"}},
			{"the in-place branch is reused on a rerun", []string{"TestCreateInPlaceBranch_RealRepo_IdempotentRerun"}},
			{"refuses a non-owner", []string{"TestOwnershipGatesRefuseForeignAndUnknown"}},
			{"refuses an owned card that start-plan never started", []string{"TestChangeCodeRefusesUnstartedClaim"}},
		},
	},
	{
		Verbs:         []string{"milestone-close"},
		Class:         NonRepeatable,
		Effects:       "dispatches the boundary review (a new round in the issue's gate ledger and review sidecar); on a finalizing verdict ticks the milestone and logs it. No commit and no card write: the agent commits with the printed trailers. Then pushes the issue branch as it stands, with a lease (#286; the trailer commit goes up at the next boundary; a failed push warns).",
		Evidence:      observeEvidence + ": checkpoints.reviews[Mx] (verdict, open_blocking).",
		Preconditions: "owned by this workspace; measured actual; the milestone's window since the previous verdict.",
		Repeat:        "dispatches a new review round. A refused (REWORK/open blocking) close changes nothing durable but the ledger; fix and re-run.",
		LostResponse:  "read the ledger and sidecar (checkpoints) before re-running — a finished review must not be re-dispatched just to learn its verdict.",
		Ends:          "the milestone is ticked; later work belongs to the next boundary.",
		Proofs: []Proof{
			{"origin's issue branch equals HEAD after the verb; a rebase is force-pushed with the lease (#286)", []string{"TestBoundaryVerbsPushTheIssueBranch", "TestBoundaryPushLeases"}},
			{"REWORK does not finalize; SHIP finalizes", []string{"TestRunMilestoneClose_REWORK_DoesNotFinalize", "TestRunMilestoneClose_SHIP_Finalizes"}},
			{"an issue changed during the review does not finalize", []string{"TestCloseCommands_IssueChangedDuringBoundaryReview_DoesNotFinalize"}},
			{"its verdict and scoped open findings are observable", []string{"TestObserveMilestonesThroughTheRealGates"}},
		},
	},
	{
		Verbs:         []string{"close"},
		Class:         NonRepeatable,
		Effects:       "dispatches the whole-issue review; on SHIP, behind a recovery receipt: an evidence commit on the branch, codecomplete on the card bound to it {token, reviewed head, evidence commit}, then a mirror commit, then a leased push of the issue branch (#286; a failed push warns). FIX-THEN-SHIP stores the receipt unstarted.",
		Evidence:      observeEvidence + ": completion (token, evidence_commit), checkpoints.reviews[close]; `sdlc issue recovery list`.",
		Preconditions: "on the issue branch; owned by this workspace; no unfinished close in progress (finish it with `sdlc issue recovery reconcile --issue N`).",
		Repeat:        "a new review and a new close generation that rebinds the card; the earlier evidence commit stays in history. Do not re-run to recover — reconcile.",
		LostResponse:  "`sdlc issue recovery reconcile --issue N` drives the receipt, probing before repeating any effect.",
		Ends:          "a landing completes the card (done); a reopen or a newer close supersedes this generation — newer by ancestry, or (#283) a close on the branch over one a rebase rewrote off it.",
		Proofs: []Proof{
			{"origin's issue branch equals HEAD after the verb; a rebase is force-pushed with the lease (#286)", []string{"TestBoundaryVerbsPushTheIssueBranch", "TestBoundaryPushLeases"}},
			{"evidence before codecomplete, bound to the reviewed head", []string{"TestTrackerCloseCommitsEvidenceAndPublishesBoundCard", "TestCompletionCommitsEvidenceBeforeCodecomplete"}},
			{"FIX-THEN-SHIP lands evidence after the fixes", []string{"TestTrackerCloseFixThenShipLandsEvidenceAfterTheFixes", "TestTrackerCloseFixThenShipSurvivesASweepingFixCommit"}},
			{"a re-close supersedes an unstarted close; an older review cannot win", []string{"TestTrackerReCloseSupersedesAnUnstartedClose", "TestNewestCloseRefusesAnOlderReviewThanTheCardsClose"}},
			{"after a rebase, a close the branch no longer contains is superseded by a re-close on the branch; a stale pre-rebase receipt still loses", []string{"TestNewestCloseAfterARebase", "TestCloseAncestorOfTreatsAnUnknownCommitAsNoAncestor", "TestTrackerCloseSurvivesARebase"}},
			{"a re-run after SHIP is a new generation", []string{"TestCloseRerunAfterShipStartsANewGeneration"}},
			{"an interrupted mirror commit is finished by reconcile", []string{"TestReconcileRetriesAnInterruptedCloseMirror"}},
			{"preconditions refuse before the review runs", []string{"TestTrackerCloseRefusesPreconditionsBeforeReview", "TestOwnershipGatesRefuseForeignAndUnknown"}},
		},
	},
	{
		Verbs:         []string{"issue recovery reconcile"},
		Class:         ConvergentRetry,
		Effects:       "drives each unfinished receipt (close, issue new, move-detail) to its end, probing an uncertain effect before repeating it; settles closes whose evidence already landed; finishes an interrupted close mirror and pushes the issue branch of a close it finished (#286).",
		Evidence:      "`sdlc issue recovery list`; " + observeEvidence + ".",
		Preconditions: "run from the checkout on the receipt's branch (another worktree is refused).",
		Repeat:        "nothing left to do: reports so and changes nothing.",
		LostResponse:  "rerun — it re-probes from the durable receipt.",
		Ends:          "a superseded close is released, never driven.",
		Proofs: []Proof{
			{"a close it finishes pushes the issue branch (#286)", []string{"TestReconciledClosePushes"}},
			{"refuses another worktree", []string{"TestRecoveryReconcileRefusesAnotherWorktree"}},
			{"an interrupted handoff is finished", []string{"TestMoveDetailInterruptedRecordIsFinishedByReconcile"}},
			{"every declared effect survives interruption", []string{"TestReceiptGeneratedInterruptionsAtEveryDeclaredEffect"}},
			{"a rerun after the mirror commit is a no-op", []string{"TestReconcileRetriesAnInterruptedCloseMirror"}},
		},
	},
	{
		Verbs:         []string{"pr"},
		Class:         ConvergentRetry,
		Effects:       "pushes the issue branch with a lease on the last-fetched copy (#286: a rebased branch publishes, an unseen remote tip refuses) and opens its pull request, or updates the open one.",
		Evidence:      "the printed PR URL; `gh pr view`.",
		Preconditions: "an issue branch (not a resting branch); handed-off details unchanged.",
		Repeat:        "in a numbered workspace: \"updated PR #N\" (converges). In an ordinary checkout `gh pr create` refuses an existing PR — check for it before re-running.",
		LostResponse:  "rerun in a numbered workspace; in an ordinary checkout check `gh pr view` first.",
		Ends:          "the PR merges or closes; a merged branch name is never reused (#148).",
		Proofs: []Proof{
			{"a rewritten branch is published with the lease (#286)", []string{"TestLandingPRPublishesARewrittenBranch"}},
			{"a repeat updates the open PR", []string{"TestLandingPRUpdatesOpenPR"}},
			{"a changed head is detected", []string{"TestLandingPRChangedHead"}},
			{"an ordinary checkout's repeat is refused by gh without change", nil},
		},
	},
	{
		Verbs:         []string{"merge"},
		Class:         ConvergentRetry,
		Effects:       "merges the PR, completes the issue's card (done, landed commit), archives the issue family on main and cleans up the branch, locally and on the remote (leased on the PR head; a failed remote delete warns, #286).",
		Evidence:      observeEvidence + ": landing.outcome, landing.archived; the printed `Recovery: sdlc merge --branch B --yes`.",
		Preconditions: "a reviewed branch whose head is unchanged since close; a clean tree; confirmation (--yes without a TTY).",
		Repeat:        "an already-merged PR resumes post-merge cleanup; a reused branch name is refused (#148); after full success from rest, refused.",
		LostResponse:  "run the printed `sdlc merge --branch B --yes`: it observes merged / integrated / archived / at rest and continues from there.",
		Ends:          "the card was reopened or closed again (another generation): completion is refused.",
		Proofs: []Proof{
			{"the landed branch leaves the remote (#286)", []string{"TestLandingDeletesTheRemoteBranch"}},
			{"resumes cleanup after a merge already happened", []string{"TestRunMerge_ResumeMergedPR_FinishesCleanup"}},
			{"refuses unmerged commits on a merged branch name", []string{"TestRunMerge_ResumeMergedPR_UnmergedCommits_Refuses"}},
			{"interrupted landings resume from observation", []string{"TestLandingInterruptedCleanup", "TestLandingInterruptedIntegration", "TestLandingRefusesUncertainty"}},
			{"a re-closed generation is left alone", []string{"TestPublishFlipLeavesAReclosedGenerationAlone"}},
			{"a reopened card is left alone", []string{"TestLandingLeavesAReopenedCardAlone"}},
			{"the archive retry proof is deterministic", []string{"TestLandingArchiveAtomicAndRetryProof", "TestDurableLandingProofSurvivesACardChangeAfterArchive"}},
		},
	},
	{
		Verbs:         []string{"push"},
		Class:         ConvergentRetry,
		Effects:       "from main: pushes, completes codecomplete cards whose evidence is now on main, archives done issues (commit + push).",
		Evidence:      observeEvidence + ": landing.",
		Preconditions: "on main, clean apart from a prepared archive move; the pre-merge gates.",
		Repeat:        "completed cards and archived issues are not touched again (inference from the convergent completion and archive steps).",
		LostResponse:  "rerun `sdlc push`: an interrupted archive (moved but uncommitted) is resumed first.",
		Ends:          "a reopened or re-closed card is not completed.",
		Proofs: []Proof{
			{"codecomplete flips then archives", []string{"TestPushPublishSequence_CodecompleteFlippedThenArchived"}},
			{"an interrupted archive is resumed", []string{"TestRecoverInterruptedArchiveCommitsAndPushes"}},
			{"a repeat after success changes nothing", nil},
		},
	},
	{
		Verbs:         []string{"move"},
		Class:         DuplicateSafeRefusal,
		Effects:       "records the relocation, switches the source slot to rest and the destination to the issue branch, verifies both, then moves the owner on the card (#277).",
		Evidence:      observeEvidence + ": assignment.claimant, workspaces.",
		Preconditions: "same repository; the source on an issue branch, the destination at rest; no git operation in progress; clean.",
		Repeat:        "the source is now at rest: refused, nothing changes.",
		LostResponse:  "a failed owner update warns and names `sdlc claim --issue N` at the destination, which finishes it; a failed first switch moved nothing and leaves no record.",
		Ends:          "another move or a reclaim overwrites the relocation.",
		Proofs: []Proof{
			{"moves the branch and its owner", []string{"TestMoveToPrimary", "TestMoveRelocatesItsOwner"}},
			{"refusals change nothing", []string{"TestMoveRefusals"}},
			{"a failed first switch leaves no record", []string{"TestMoveFirstSwitchFailureLeavesNoRecord"}},
			{"a failed owner update is repaired by claim", []string{"TestRelocationAfterMoveAndRepair"}},
		},
	},
	{
		Verbs:         []string{"issue set-status", "set-status", "issue set-title", "issue set-estimate", "issue set-github"},
		Class:         ConvergentRetry,
		Effects:       "one compare-and-swap on the card field (entering working also stamps the claimant, #277); a local mirror refresh. Reopening abandoned work (#286) first restores its branch from the archive ref (fetch, branch, merge main, un-archive commit, push), then after the card write commits the mirror, pushes and deletes the ref.",
		Evidence:      observeEvidence + ": card.",
		Preconditions: "the lifecycle guards, including `owned` on start: an unowned open card is claimed first (#283) (--force waives guards, never a foreign owner); done and codecomplete belong to close and merge; wontfix/punt from started work belong to `sdlc abandon` (#286, not waivable).",
		Repeat:        "\"already has that …\" — no write.",
		LostResponse:  "rerun the same command — the card decides. A concurrent change refuses (\"changed concurrently\").",
		Ends:          "another card change since you read it.",
		Proofs: []Proof{
			{"started work ends only through abandon; a reopen restores, un-archives and resumes after a conflict or a failed push (#286)", []string{"TestSetStatusRedirectsStartedWorkToAbandon", "TestReopenRestoresAnAbandonedIssue", "TestReopenStopsOnAConflictThenResumes", "TestReopenRerunAfterAFailedPush"}},
			{"guards and claimant stamping", []string{"TestStatusDecisionRecordsOrRefusesTheClaimant", "TestCheckTransitionGuards_ReopenNeedsLogEntry"}},
			{"a lost response is settled by rerunning", []string{"TestSetStatusRerunSettlesALostResponse"}},
		},
	},
	{
		Verbs:         []string{"issue new"},
		Class:         NonRepeatable,
		Effects:       "behind a creation receipt: reserves the next ID on the tracker, then writes the details locally (committed narrowly on a feature branch).",
		Evidence:      "the printed path; `sdlc issue recovery list`.",
		Preconditions: "a branch (not detached).",
		Repeat:        "files another issue with a new ID.",
		LostResponse:  "`sdlc issue recovery reconcile` resumes the receipt (a reservation that published nothing is released).",
		Ends:          "the details land on main (`sdlc issue move-detail`).",
		Proofs: []Proof{
			{"concurrent filings get distinct IDs", []string{"TestIssueNewRaceAllocatesDistinctIDs", "TestCreationLostRaceReallocatesWithoutDuplicateID"}},
			{"an uncertain push resumes from the receipt", []string{"TestCreationUncertainPushResumesFromDurableReceipt"}},
		},
	},
	{
		Verbs:         []string{"issue move-detail"},
		Class:         DuplicateSafeRefusal,
		Effects:       "the first-publication case of `issue publish` (#284), for one issue: behind a transfer receipt, records the handoff on the card, publishes the initial details to main, removes the source copy.",
		Evidence:      "the details on main; " + observeEvidence + ".",
		Preconditions: "no unfinished receipt; a free destination; no hand-edited card field.",
		Repeat:        "refused once the handoff exists (inference: the destination is occupied).",
		LostResponse:  "`sdlc issue recovery reconcile` finishes an interrupted handoff.",
		Ends:          "the details are on main; the owner publishes later edits with `issue publish` (#284), or they ride the issue branch.",
		Proofs: []Proof{
			{"an interrupted handoff is finished by reconcile", []string{"TestMoveDetailInterruptedRecordIsFinishedByReconcile"}},
			{"issue publish's first publication is this transfer", []string{"TestPublishFirstPublicationIsMoveDetail"}},
			{"refuses an occupied destination", []string{"TestMoveDetailRefusesExistingDestinationAndUnreadableSource"}},
		},
	},
	{
		Verbs:         []string{"issue sync"},
		Class:         ConvergentRetry,
		Effects:       "in a tracker repository, nothing: retired to a pointer (#284) — commit details with git on the issue branch, publish them with `issue publish`. In a legacy repository, commits the issue's details locally; pushes nothing.",
		Evidence:      "`git log -- <details>`.",
		Preconditions: "a legacy repository (a tracker repository always refuses, naming git and `issue publish`).",
		Repeat:        "nothing new to commit (inference).",
		LostResponse:  "local only; rerun.",
		Ends:          "not applicable: a local commit only.",
		Proofs: []Proof{
			{"commits locally and never pushes", []string{"TestIssueSync_DefaultDoesNotPush", "TestIssueSync_FromFeatureBranchCommitsOnThatBranch"}},
			{"retired in a tracker repository, naming git and issue publish", []string{"TestLegacyIssueEntrypointsInATrackedRepository"}},
			{"a repeat with nothing new changes nothing", nil},
		},
	},
	{
		Verbs:         []string{"issue restore"},
		Class:         ConvergentRetry,
		Effects:       "one local commit on the current branch setting every copy of each named issue's details to main's version (removing a copy main lacks), for the issues the transfer guard refuses here (#285). Pushes nothing; the card is untouched.",
		Evidence:      "`git log -1` on the branch; `sdlc pr --dry-run` passes the transfer guard.",
		Preconditions: "an issue tracker repository; a checkout that does not own the issue (the owner merges main instead); each details file to restore is clean, or already holds main's version (an interrupted restore).",
		Repeat:        "nothing left to restore: \"nothing to restore\", no commit.",
		LostResponse:  "local only; rerun — a file already reset to main's version is committed, not refused.",
		Ends:          "not applicable: a local commit only.",
		Proofs: []Proof{
			{"makes a refused branch land with one commit; a repeat commits nothing", []string{"TestIssueRestoreMakesAStaleFilingBranchLand"}},
			{"removes a copy main archived", []string{"TestIssueRestoreRemovesWhatMainArchived"}},
			{"refuses a dirty details file; finishes an interrupted restore", []string{"TestIssueRestoreRefusesADirtyDetailsFile", "TestIssueRestoreResumesAnInterruptedRestore"}},
			{"refuses in the owner's checkout, where the edit is the owner's", []string{"TestIssueRestoreRefusesTheOwnersOwnEdit"}},
		},
	},
	{
		Verbs:         []string{"abandon"},
		Class:         ConvergentRetry,
		Effects:       "started work (#286): a `#N: log: abandon (…)` commit on the issue branch; the tip pushed to `refs/ariadne/abandoned/NNNNNN`; one card compare-and-swap to wontfix/punt recording {ref, branch, head} (owner kept as attribution); one narrow main commit archiving the details (mirroring the terminal card) and the issue's plan artifacts on main; the branch deleted on the remote (when the kept tip contains it), the checkout returned to rest, the local branch deleted. An open issue: the card (with an empty record) and the archive only.",
		Evidence:      observeEvidence + ": card.status; `git ls-remote <remote> refs/ariadne/abandoned/NNNNNN`; main's history archive.",
		Preconditions: "an issue tracker repository; owned by this workspace; a clean tree; the model has an abandon/defer edge from the status; started work runs from its issue branch.",
		Repeat:        "a terminal card carrying the abandon record is recognised before the branch checks, so a rerun from the resting branch finishes the archive and the branch deletion; each step is skipped when done (the note commit is the tip, the archive ref already holds the tip, main has no live copy, the branch is gone).",
		LostResponse:  "rerun the same command — the card decides: not yet terminal repeats from the note (recognised), terminal resumes at the archive.",
		Ends:          "a reopen (`sdlc issue set-status working`) restores the branch from the archive ref and clears the record; otherwise the ref and the record stay as the work's archive.",
		Proofs: []Proof{
			{"started work is kept, the card ends, the details archive, the branch goes; a repeat changes nothing", []string{"TestAbandonStartedWork"}},
			{"an open issue ends with an empty record and an archive", []string{"TestAbandonOpenIssue"}},
			{"each refusal names its own check, before any effect", []string{"TestAbandonRefusals", "TestAbandonDecision"}},
			{"an interruption at any step, from the branch or from rest, is finished by rerunning", []string{"TestAbandonRerunResumes"}},
		},
	},
	{
		Verbs:         []string{"issue publish"},
		Class:         ConvergentRetry,
		Effects:       "per issue (#284): a first publication (details not on main) is `move-detail`'s receipt-driven transfer; details already on main are the owner's edits, published to main in one narrow commit for the set (a moved main is first brought in on a resting branch). Then a resting branch fast-forwards, the issue's own branch commits the same bytes, and another issue's branch takes its copy back. Never touches the tracker.",
		Evidence:      "the details on main (`git log origin/main -- <details>`); " + observeEvidence + ".",
		Preconditions: "first publication: a free destination, no unfinished receipt. Republish: this workspace owns each card (re-checked against a fresh tracker read before the push), local details present without conflict markers, and main's copy unchanged since this checkout's merge base — on a resting branch a moved main is brought in by a three-way merge first (a conflict leaves markers and refuses); elsewhere the refusal names the steps.",
		Repeat:        "main already holds the details: nothing is written; the checkout is finished as after a publish (rest fast-forwards; the issue's own branch commits; another issue's branch takes its copy back).",
		LostResponse:  "rerun the same command — main decides: the details already there make the rerun a finish-only pass. An interrupted first publication finishes with `sdlc issue recovery reconcile`.",
		Ends:          "the details are on main; a later publish needs the claim again.",
		Proofs: []Proof{
			{"republishing judges local, base and main bodies, never overwriting a moved main", []string{"TestRepublishDecision", "TestPublishRefusals"}},
			{"a set's edits land in one main commit; the rest ends equal to main", []string{"TestPublishOwnedEditsFromRest"}},
			{"an issue branch commits the published bytes", []string{"TestPublishFromAnIssueBranch"}},
			{"ownership is re-checked before the push", []string{"TestPublishRefusesAReclaimBeforeThePush"}},
			{"a moved main is brought in on a resting branch; markers never publish; a failed bring-in keeps the edits", []string{"TestPublishBringsAMovedMainIn", "TestPublishRefusesConflictMarkers", "TestPublishBringInSetAsideIsAllOrNothing", "TestPublishBringInWriteBackFailureNamesTheCopies"}},
			{"off a resting branch the refusal's steps run from the refused state", []string{"TestPublishMovedMainOnTheIssueBranchRemedy", "TestPublishMovedMainFromAnotherBranchRemedy", "TestPublishFromAnotherIssuesBranchCommitsNothingThere"}},
			{"a lost response reruns into a finish-only pass", []string{"TestPublishRerunAfterALostResponse"}},
			{"a first publication is move-detail's transfer", []string{"TestPublishFirstPublicationIsMoveDetail"}},
		},
	},
	{
		Verbs:         []string{"unclaim"},
		Class:         ConvergentRetry,
		Effects:       "the owner's release (#284); the status never changes. An open claim: its unpublished edits are published (`issue publish`) while still held, then one tracker commit clears every named owner and records the release (who let go). Started work, one issue at a time: a handoff — the optional note is committed on the issue branch, the branch is pushed (leased on the copy this checkout last fetched: the owner is its only writer, but an unseen remote tip is never overwritten), the card records the release with branch and tip, and the checkout returns to rest.",
		Evidence:      observeEvidence + ": assignment.claimant (absent once released).",
		Preconditions: "this workspace owns every card, on a status that holds the lock; a refused publish keeps the claim. A handoff runs from the issue's branch with a clean tree, untracked files included.",
		Repeat:        "cards this workspace already released: \"already released\" / \"already handed off by this workspace\" — the checkout is finished (rest fast-forwards; a handoff's checkout returns to rest).",
		LostResponse:  "rerun the same command — the cards decide: a release this workspace recorded is recognised and only the checkout is finished.",
		Ends:          "any claim takes the lock again and spends the release.",
		Proofs: []Proof{
			{"only the owner releases; the status never moves; a rerun is the no-op", []string{"TestUnclaimDecision"}},
			{"edits are published, then the set released in one tracker commit", []string{"TestUnclaimPublishesThenReleases"}},
			{"refuses unowned and foreign cards", []string{"TestUnclaimRefusals"}},
			{"a lost response reruns into the no-op", []string{"TestUnclaimRerunAfterALostResponse"}},
			{"a claim spends the release", []string{"TestClaimClearsARelease"}},
			{"a handoff pushes the branch and records its tip; refuses uncommitted work and the wrong branch", []string{"TestHandoffAndTakeover", "TestHandoffRefusals"}},
			{"a handoff's lost card write is finished by rerunning", []string{"TestHandoffRerunAfterALostResponse"}},
			{"the handoff lease refuses a remote tip this checkout never saw", []string{"TestHandoffLeaseRefusesAnUnseenRemoteTip"}},
			{"a note is filed once per attempt: same-day text, or a handoff's own note commit across midnight; another release's identical note is filed again", []string{"TestUnclaimNoteIsConvergent", "TestUnclaimNoteIsKeyedToTheAttempt", "TestHandoffRecognisesItsNoteCommit"}},
		},
	},
	{
		Verbs:         []string{"issue show"},
		Class:         ReadOnly,
		Effects:       "none besides the tracker fetch's remote-tracking ref update.",
		Evidence:      "its own output (`--json`, schema_version 1, #279).",
		Preconditions: "none; any checkout of the repository, or --repo.",
		Repeat:        "a fresh observation.",
		LostResponse:  "rerun.",
		Ends:          "each answer is as of its observed_at and tracker commit; stale/unknown sections are not negative evidence.",
		Proofs: []Proof{
			{"writes nothing local", []string{"TestObserveAParkedSlotFromAnotherCheckout"}},
			{"stale reads say so", []string{"TestObserveStaleTrackerSaysSo"}},
		},
	},
	{
		Verbs:         []string{"fleet inventory"},
		Class:         ReadOnly,
		Effects:       "none besides each repository's tracker fetch updating its remote-tracking ref (the same read `issue show` performs).",
		Evidence:      "its own output (`--json`, schema_version 1): rows[].claims and claims_state, machine, dangling_claims (#288); slots[] with each member's verdict and reasons (#289).",
		Preconditions: "none; any path inside the fleet (--path).",
		Repeat:        "a fresh observation.",
		LostResponse:  "rerun.",
		Ends:          "each answer is as of its reads; stale, partial and unknown states are not negative evidence, and a slot verdict is an observation an action re-checks at action time.",
		Proofs: []Proof{
			{"claims placed per worktree from one read per repository; a removed slot's claim is dangling", []string{"TestFleetInventoryPlacesClaims"}},
			{"stale reads say so and keep the claims", []string{"TestFleetInventoryStaleClaimsSaySo"}},
			{"a failed or partial read is never \"no claims\"", []string{"TestPlaceClaims"}},
			{"one readiness verdict per slot over its declared checkouts; a failed probe is never ready", []string{"TestFleetInventorySlotReadiness", "TestJudgeCheckout"}},
		},
	},
}

// Exempt are mutating commands outside the issue workflow's recovery
// contracts, each with the reason it needs none here.
var Exempt = map[string]string{
	"issue migrate":      "one-time tracker cutover with its own --apply/--reconcile procedure (atlas: issue-tracker-migration)",
	"project new":        "project artifacts, not the issue workflow",
	"project set-status": "project artifacts, not the issue workflow",
	"project retro":      "project artifacts, not the issue workflow",
	"project close":      "project artifacts, not the issue workflow",
	"migrate":            "cross-repository artifact move tool (#179), outside the issue workflow",
	"fetch":              "refreshes remote-tracking refs only; no workflow state",
}
