// Package processmanual assembles the "process manual" — every always-on
// injection source unrolled into one linked markdown document (issue #153,
// `sdlc process-manual`). The core is pure (InjectionSource + renderManual); the
// IO shell of collectors lives in collect.go / memory.go.
package processmanual

import (
	"fmt"
	"sort"
	"strings"
)

// Kind groups injection sources into manual sections.
type Kind string

const (
	KindSDLCPrompt  Kind = "sdlc-prompt"
	KindHelpText    Kind = "help-text"
	KindSkill       Kind = "skill"
	KindLessons     Kind = "lessons"
	KindAgentsChain Kind = "agents-chain"
	KindMemory      Kind = "memory"
	// KindFileEdit is not an injection source: it marks an Edit/Write/MultiEdit
	// tool call, consumed only by the friction audit's firing-order detector
	// (skill-late, #172 M2). parseEvents drops it from the --session report.
	KindFileEdit Kind = "file-edit"
)

// InjectionSource is one catalogued point where content enters an agent's context.
type InjectionSource struct {
	Kind  Kind
	Title string
	When  string // prose trigger: what injects this content
	Link  string // repo-root-relative path (+ optional #anchor)
	Body  string // full text for code-generated prompts; excerpt for file-backed sources
}

// sections fixes the display order and headings for each Kind.
var sections = []struct {
	kind    Kind
	heading string
}{
	{KindSDLCPrompt, "## sdlc-injected prompts"},
	{KindHelpText, "## Help text"},
	{KindSkill, "## Skills"},
	{KindLessons, "## Lessons"},
	{KindAgentsChain, "## AGENTS chain"},
	{KindMemory, "## Persisted memories"},
}

// renderManual is pure: sources → linked markdown, grouped by Kind in `sections`
// order. linkPrefix is prepended to every Link so the doc resolves from wherever
// it is written ("" = paths from repo root).
func renderManual(sources []InjectionSource, linkPrefix string) string {
	byKind := map[Kind][]InjectionSource{}
	for _, s := range sources {
		byKind[s.Kind] = append(byKind[s.Kind], s)
	}
	var b strings.Builder
	b.WriteString("# Process manual\n\n")
	b.WriteString("_Generated by `sdlc process-manual`. Every always-on injection source, linked to its origin. Do not hand-edit — regenerate._\n\n")
	for _, sec := range sections {
		items := byKind[sec.kind]
		if len(items) == 0 {
			continue
		}
		sort.SliceStable(items, func(i, j int) bool { return items[i].Title < items[j].Title })
		b.WriteString(sec.heading + "\n\n")
		for _, s := range items {
			switch {
			case s.Link == "":
				// No source to link (e.g. the "no memories found" note).
				fmt.Fprintf(&b, "### %s\n\n", s.Title)
			case strings.HasPrefix(s.Link, "/"):
				// Absolute path (outside-repo, e.g. persisted memories) — the
				// relative linkPrefix does not apply.
				fmt.Fprintf(&b, "### [%s](%s)\n\n", s.Title, s.Link)
			default:
				fmt.Fprintf(&b, "### [%s](%s%s)\n\n", s.Title, linkPrefix, s.Link)
			}
			if s.When != "" {
				fmt.Fprintf(&b, "**When:** %s\n\n", s.When)
			}
			if s.Body != "" {
				// A Body carrying its own markdown headings (the inlined judge
				// prompts embed `#`/`##` — the ARCH registry, checklists) would
				// otherwise hijack the manual's section structure. Fence it (a
				// `~~~` block, which won't collide with backtick fences inside the
				// prompt) so headings render as literal text.
				fenced := hasHeadingLine(s.Body)
				if fenced {
					b.WriteString("~~~\n")
				}
				b.WriteString(s.Body)
				if !strings.HasSuffix(s.Body, "\n") {
					b.WriteString("\n")
				}
				if fenced {
					b.WriteString("~~~\n")
				}
				b.WriteString("\n")
			}
		}
	}
	return b.String()
}

// hasHeadingLine reports whether any line is an ATX markdown heading (`# ` …
// `###### `). Such a body must be fenced before inlining so it can't corrupt the
// manual's own heading structure.
func hasHeadingLine(s string) bool {
	for _, ln := range strings.Split(s, "\n") {
		t := strings.TrimSpace(ln)
		n := 0
		for n < len(t) && t[n] == '#' {
			n++
		}
		if n >= 1 && n <= 6 && n < len(t) && t[n] == ' ' {
			return true
		}
	}
	return false
}
