// Package vocab is the Go binding for the formal vocabulary layer (ariadne#122).
// It embeds the cue-exported `issue` noun JSON once and exposes read-only
// predicates over the issue lifecycle.
//
// Single source of truth: construct/vocabulary/issue.cue. This package is the
// canonical *Go placement* — every Go consumer (sdlc, and any future one) imports
// it, so the import graph distributes one copy and the model is never re-encoded
// per consumer. The committed issue.json is regenerated by `make vocab-embed`
// (go:generate below); it stays committed so a standalone `go build` works.
package vocab

import (
	"path/filepath"

	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

//go:generate sh -c "vocabulary export --noun issue > issue.json"

//go:embed issue.json
var issueJSON []byte

// Transition is one lifecycle edge (the model's verbs). Guards name the
// effectful preconditions whose implementations live in sdlc (e.g. the close
// gate); the names travel, the implementations don't.
type Transition struct {
	From   string   `json:"from"`
	To     string   `json:"to"`
	Event  string   `json:"event"`
	Guards []string `json:"guards"`
}

// Discovery is the parsed `discovery:` block: where instances of the issue noun
// and its id-keyed family (durable plan + boundary-review sidecars) live, and
// where they move on close/merge. Repo-relative — a consumer joins these to a
// repo root. Single source: construct/vocabulary/issue.cue. Consumed by
// parley.nvim#116 (home) and sdlc resolve #144 (the full family).
type Discovery struct {
	Home    string `json:"home"`    // active issue instances
	Glob    string `json:"glob"`    // filename glob within Home
	Archive string `json:"archive"` // terminal issues + family move here on close/merge
	Plans   string `json:"plans"`   // active durable plan + boundary-review sidecars
}

// Section is one body section of the new-issue creation template: a heading
// name and an optional literal seed line written beneath it in a blank issue.
// Ordered (list order = created-file order). Source: construct/vocabulary/issue.cue
// `scaffold.sections`.
type Section struct {
	Name string `json:"name"`
	Seed string `json:"seed"`
}

// Scaffold is the parsed `scaffold:` block — the on-disk creation-template shape
// that sdlc's `issue new` renders from (#145) instead of a hardcoded Go template.
type Scaffold struct {
	Sections []Section `json:"sections"`
}

// IssueModel is the read-only, parsed `issue` noun: status categories, the
// lifecycle transition graph, and per-status semantics. Derived from
// construct/vocabulary/issue.cue at generate time; never hand-edited.
type IssueModel struct {
	Categories map[string][]string `json:"categories"` // "open"/"active"/"terminal" → status names
	When       map[string]string   `json:"when"`       // status → one-line semantics
	// Disc holds the discovery: block; the field is unexported-name-clash-avoiding
	// (Disc, not Discovery) so the Discovery() accessor can carry the read name.
	Disc      Discovery    `json:"discovery"`
	Lifecycle []Transition `json:"lifecycle"`
	// Scaf holds the scaffold: block; unexported-name-clash-avoiding (Scaf, not
	// Scaffold) so the Sections() accessor can carry the read name — mirrors Disc.
	Scaf Scaffold `json:"scaffold"`
}

var issueModel = mustLoadIssue()

func mustLoadIssue() *IssueModel {
	var m IssueModel
	if err := json.Unmarshal(issueJSON, &m); err != nil {
		panic(fmt.Sprintf("vocab: corrupt embedded issue.json (run `make vocab-embed`): %v", err))
	}
	return &m
}

// Issue returns the embedded `issue` model.
func Issue() *IssueModel { return issueModel }

// Discovery returns the issue noun's location model (home/glob/archive/plans),
// so consumers derive artifact locations from the model instead of hardcoding
// them (ariadne#144).
func (m *IssueModel) Discovery() Discovery { return m.Disc }

// ArchiveKind names one per-kind archive subdir under the archive root (#181
// layout, widened kind-keyed for #180): issues under root/issues, plans +
// review sidecars under root/plans, done/dropped projects under root/projects.
type ArchiveKind string

const (
	ArchiveIssues   ArchiveKind = "issues"
	ArchivePlans    ArchiveKind = "plans"
	ArchiveProjects ArchiveKind = "projects"
)

// ArchiveSubdir derives one kind's archive dir from an archive ROOT. Go-owned
// rather than cue-encoded because writers take --history-dir / WF_HISTORY_DIR
// root overrides and must derive from an arbitrary root (and widening the
// cue's `archive` string to a struct would break downstream JSON consumers of
// the discovery export). THE single derivation point — consumers route through
// it; nothing concatenates these subdir literals elsewhere (a guard test
// enforces this). Reads stay tolerant of the pre-#181 flat layout; writes emit
// only into these subdirs.
func ArchiveSubdir(root string, kind ArchiveKind) string {
	return filepath.Join(root, string(kind))
}

// Sections returns the ordered creation-template body sections, so the issue
// scaffolder derives the section list from the model instead of hardcoding it
// (ariadne#145).
func (m *IssueModel) Sections() []Section { return m.Scaf.Sections }

// InitialStatus returns the status a newly-created issue carries — the sole
// member of the `open` category — so the scaffolder's `status:` line derives from
// the model, not a Go literal (ariadne#145). Falls back to "open" only if a
// corrupt model defines no open status (mustLoadIssue already panics on corrupt
// JSON, so this is a belt-and-suspenders guard, not a real path).
func (m *IssueModel) InitialStatus() string {
	open := m.Categories["open"]
	if len(open) == 0 {
		return "open"
	}
	return open[0]
}

func (m *IssueModel) inCategory(cat, s string) bool {
	return inCat(m.Categories, cat, s)
}

// IsTerminal reports whether s is a closed status (done/wontfix/punt).
func (m *IssueModel) IsTerminal(s string) bool { return m.inCategory("terminal", s) }

// IsActive reports whether s is an in-progress status (working/blocked).
func (m *IssueModel) IsActive(s string) bool { return m.inCategory("active", s) }

// IsOpen reports whether s is the not-yet-started status.
func (m *IssueModel) IsOpen(s string) bool { return m.inCategory("open", s) }

// issueCategoryOrder is the issue noun's category ordering for AllStatuses.
var issueCategoryOrder = []string{"open", "active", "terminal"}

// AllStatuses returns every status, ordered open → active → terminal.
func (m *IssueModel) AllStatuses() []string {
	return allStatuses(m.Categories, issueCategoryOrder)
}

// CanTransition reports whether the lifecycle declares a from→to edge. As of
// ariadne#122 M4 this is ENFORCED: `sdlc issue set-status` refuses a transition
// the model doesn't declare, with a `--force` escape (claim/close perform fixed
// legal transitions and stay ungated).
func (m *IssueModel) CanTransition(from, to string) bool {
	return canTransition(m.Lifecycle, from, to)
}

// LegalTransitions returns the statuses `from` may legally transition to, in
// lifecycle order, de-duplicated. Empty when `from` is unknown or a true
// dead-end. Used to render the legal targets in set-status's refusal message.
func (m *IssueModel) LegalTransitions(from string) []string {
	return legalTransitions(m.Lifecycle, from)
}

// ── Help-text renders (#125) ──
// These produce the model-derived portions of `sdlc`'s help text, so the prose
// can't drift from the model. They render the FACTS only (status set + semantics +
// legal edges) in a NEUTRAL form — the editorial framing (e.g. "--force overrides",
// "use sdlc close") stays hand-written in the helptext `.md` around the placeholder.
// All reuse AllStatuses() ordering (open → active → terminal) and are pure.

// RenderLifecycleHelp renders the full lifecycle reference: a STATUSES section
// (each status + its one-line `When` semantics) and a LEGAL TRANSITIONS section
// (each status → its legal targets). 2-space indented to match the help style.
func (m *IssueModel) RenderLifecycleHelp() string {
	return renderLifecycleHelp(m.AllStatuses(), m.When, m.Lifecycle)
}

// StatusNames joins the status set with sep, in AllStatuses order — for an inline
// help restatement like `open | working | blocked | done | wontfix | punt`.
func (m *IssueModel) StatusNames(sep string) string {
	return strings.Join(m.AllStatuses(), sep)
}

// StatusGloss renders the status set as a compact dot-separated gloss:
// “ `open` <when> · `working` <when> · … “ — for a one-line inline reference.
func (m *IssueModel) StatusGloss() string {
	parts := make([]string, 0, len(m.When))
	for _, s := range m.AllStatuses() {
		parts = append(parts, fmt.Sprintf("`%s` %s", s, m.When[s]))
	}
	return strings.Join(parts, " · ")
}
