// Package vocab is the Go binding for the formal vocabulary layer (ariadne#122).
// It embeds the cue-exported `issue` noun JSON once and exposes read-only
// predicates over the issue lifecycle.
//
// Single source of truth: construct/vocabulary/issue.cue. This package is the
// canonical *Go placement* — every Go consumer (sdlc, and any future one) imports
// it, so the import graph distributes one copy and the model is never re-encoded
// per consumer. The committed issue.json is regenerated by `make vocab-embed`
// (go:generate below); it stays committed so a standalone `go build` works.
package vocab

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

//go:generate sh -c "vocabulary export --noun issue > issue.json"

//go:embed issue.json
var issueJSON []byte

// Transition is one lifecycle edge (the model's verbs). Guards name the
// effectful preconditions whose implementations live in sdlc (e.g. the close
// gate); the names travel, the implementations don't.
type Transition struct {
	From   string   `json:"from"`
	To     string   `json:"to"`
	Event  string   `json:"event"`
	Guards []string `json:"guards"`
}

// Discovery is the parsed `discovery:` block: where instances of the issue noun
// and its id-keyed family (durable plan + boundary-review sidecars) live, and
// where they move on close/merge. Repo-relative — a consumer joins these to a
// repo root. Single source: construct/vocabulary/issue.cue. Consumed by
// parley.nvim#116 (home) and sdlc resolve #144 (the full family).
type Discovery struct {
	Home    string `json:"home"`    // active issue instances
	Glob    string `json:"glob"`    // filename glob within Home
	Archive string `json:"archive"` // terminal issues + family move here on close/merge
	Plans   string `json:"plans"`   // active durable plan + boundary-review sidecars
}

// IssueModel is the read-only, parsed `issue` noun: status categories, the
// lifecycle transition graph, and per-status semantics. Derived from
// construct/vocabulary/issue.cue at generate time; never hand-edited.
type IssueModel struct {
	Categories map[string][]string `json:"categories"` // "open"/"active"/"terminal" → status names
	When       map[string]string   `json:"when"`       // status → one-line semantics
	// Disc holds the discovery: block; the field is unexported-name-clash-avoiding
	// (Disc, not Discovery) so the Discovery() accessor can carry the read name.
	Disc      Discovery    `json:"discovery"`
	Lifecycle []Transition `json:"lifecycle"`
}

var issueModel = mustLoadIssue()

func mustLoadIssue() *IssueModel {
	var m IssueModel
	if err := json.Unmarshal(issueJSON, &m); err != nil {
		panic(fmt.Sprintf("vocab: corrupt embedded issue.json (run `make vocab-embed`): %v", err))
	}
	return &m
}

// Issue returns the embedded `issue` model.
func Issue() *IssueModel { return issueModel }

// Discovery returns the issue noun's location model (home/glob/archive/plans),
// so consumers derive artifact locations from the model instead of hardcoding
// them (ariadne#144).
func (m *IssueModel) Discovery() Discovery { return m.Disc }

func (m *IssueModel) inCategory(cat, s string) bool {
	for _, v := range m.Categories[cat] {
		if v == s {
			return true
		}
	}
	return false
}

// IsTerminal reports whether s is a closed status (done/wontfix/punt).
func (m *IssueModel) IsTerminal(s string) bool { return m.inCategory("terminal", s) }

// IsActive reports whether s is an in-progress status (working/blocked).
func (m *IssueModel) IsActive(s string) bool { return m.inCategory("active", s) }

// IsOpen reports whether s is the not-yet-started status.
func (m *IssueModel) IsOpen(s string) bool { return m.inCategory("open", s) }

// AllStatuses returns every status, ordered open → active → terminal.
func (m *IssueModel) AllStatuses() []string {
	var out []string
	for _, cat := range []string{"open", "active", "terminal"} {
		out = append(out, m.Categories[cat]...)
	}
	return out
}

// CanTransition reports whether the lifecycle declares a from→to edge. As of
// ariadne#122 M4 this is ENFORCED: `sdlc issue set-status` refuses a transition
// the model doesn't declare, with a `--force` escape (claim/close perform fixed
// legal transitions and stay ungated).
func (m *IssueModel) CanTransition(from, to string) bool {
	for _, t := range m.Lifecycle {
		if t.From == from && t.To == to {
			return true
		}
	}
	return false
}

// LegalTransitions returns the statuses `from` may legally transition to, in
// lifecycle order, de-duplicated. Empty when `from` is unknown or a true
// dead-end. Used to render the legal targets in set-status's refusal message.
func (m *IssueModel) LegalTransitions(from string) []string {
	var out []string
	seen := map[string]bool{}
	for _, t := range m.Lifecycle {
		if t.From == from && !seen[t.To] {
			out = append(out, t.To)
			seen[t.To] = true
		}
	}
	return out
}

// ── Help-text renders (#125) ──
// These produce the model-derived portions of `sdlc`'s help text, so the prose
// can't drift from the model. They render the FACTS only (status set + semantics +
// legal edges) in a NEUTRAL form — the editorial framing (e.g. "--force overrides",
// "use sdlc close") stays hand-written in the helptext `.md` around the placeholder.
// All reuse AllStatuses() ordering (open → active → terminal) and are pure.

// RenderLifecycleHelp renders the full lifecycle reference: a STATUSES section
// (each status + its one-line `When` semantics) and a LEGAL TRANSITIONS section
// (each status → its legal targets). 2-space indented to match the help style.
func (m *IssueModel) RenderLifecycleHelp() string {
	statuses := m.AllStatuses()
	width := 0
	for _, s := range statuses {
		if len(s) > width {
			width = len(s)
		}
	}
	var b strings.Builder
	b.WriteString("STATUSES\n\n")
	for _, s := range statuses {
		b.WriteString(fmt.Sprintf("  %-*s  %s\n", width, s, m.When[s]))
	}
	b.WriteString("\nLEGAL TRANSITIONS\n\n")
	for _, s := range statuses {
		targets := m.LegalTransitions(s)
		if len(targets) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("  %-*s  → %s\n", width, s, strings.Join(targets, ", ")))
	}
	return strings.TrimRight(b.String(), "\n")
}

// StatusNames joins the status set with sep, in AllStatuses order — for an inline
// help restatement like `open | working | blocked | done | wontfix | punt`.
func (m *IssueModel) StatusNames(sep string) string {
	return strings.Join(m.AllStatuses(), sep)
}

// StatusGloss renders the status set as a compact dot-separated gloss:
// “ `open` <when> · `working` <when> · … “ — for a one-line inline reference.
func (m *IssueModel) StatusGloss() string {
	parts := make([]string, 0, len(m.When))
	for _, s := range m.AllStatuses() {
		parts = append(parts, fmt.Sprintf("`%s` %s", s, m.When[s]))
	}
	return strings.Join(parts, " · ")
}
