// Package vocab is the Go binding for the formal vocabulary layer (ariadne#122).
// It embeds the cue-exported `issue` noun JSON once and exposes read-only
// predicates over the issue lifecycle.
//
// Single source of truth: construct/vocabulary/issue.cue. This package is the
// canonical *Go placement* — every Go consumer (sdlc, and any future one) imports
// it, so the import graph distributes one copy and the model is never re-encoded
// per consumer. The committed issue.json is regenerated by `make vocab-embed`
// (go:generate below); it stays committed so a standalone `go build` works.
package vocab

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

//go:generate sh -c "vocabulary export --noun issue > issue.json"

//go:embed issue.json
var issueJSON []byte

// Transition is one lifecycle edge (the model's verbs). Guards name the
// effectful preconditions whose implementations live in sdlc (e.g. the close
// gate); the names travel, the implementations don't.
type Transition struct {
	From   string   `json:"from"`
	To     string   `json:"to"`
	Event  string   `json:"event"`
	Guards []string `json:"guards"`
}

// IssueModel is the read-only, parsed `issue` noun: status categories, the
// lifecycle transition graph, and per-status semantics. Derived from
// construct/vocabulary/issue.cue at generate time; never hand-edited.
type IssueModel struct {
	Categories map[string][]string `json:"categories"` // "open"/"active"/"terminal" → status names
	When       map[string]string   `json:"when"`        // status → one-line semantics
	Lifecycle  []Transition        `json:"lifecycle"`
}

var issueModel = mustLoadIssue()

func mustLoadIssue() *IssueModel {
	var m IssueModel
	if err := json.Unmarshal(issueJSON, &m); err != nil {
		panic(fmt.Sprintf("vocab: corrupt embedded issue.json (run `make vocab-embed`): %v", err))
	}
	return &m
}

// Issue returns the embedded `issue` model.
func Issue() *IssueModel { return issueModel }

func (m *IssueModel) inCategory(cat, s string) bool {
	for _, v := range m.Categories[cat] {
		if v == s {
			return true
		}
	}
	return false
}

// IsTerminal reports whether s is a closed status (done/wontfix/punt).
func (m *IssueModel) IsTerminal(s string) bool { return m.inCategory("terminal", s) }

// IsActive reports whether s is an in-progress status (working/blocked).
func (m *IssueModel) IsActive(s string) bool { return m.inCategory("active", s) }

// IsOpen reports whether s is the not-yet-started status.
func (m *IssueModel) IsOpen(s string) bool { return m.inCategory("open", s) }

// AllStatuses returns every status, ordered open → active → terminal.
func (m *IssueModel) AllStatuses() []string {
	var out []string
	for _, cat := range []string{"open", "active", "terminal"} {
		out = append(out, m.Categories[cat]...)
	}
	return out
}

// CanTransition reports whether the lifecycle declares a from→to edge. NOTE:
// this is the model's view of legal transitions; sdlc does not (yet) gate
// set-status on it — see ariadne#122 M3 (the tightening decision).
func (m *IssueModel) CanTransition(from, to string) bool {
	for _, t := range m.Lifecycle {
		if t.From == from && t.To == to {
			return true
		}
	}
	return false
}
